- hosts: pvenodes
  tasks:

  - name: create Ansible user
    user:
      name: ansible
      shell: '/bin/bash'

  - name: add ansible to sudoers
    copy:
      src: sudoer_ansible
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: 0440
