---
 
 - hosts: all
   become: true
   pre_tasks:
 
   - name: install updates (Ubuntu)
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Ubuntu"
  
 - hosts: web_servers
   tasks:
   - name: install apache2 ans php packages for Ubuntu
     tags: apache,apache2,ubuntu
     apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
     when: ansible_distribution == "Ubuntu"

