---
 
 - hosts: 192.168.53.18
   become: true
   pre_tasks:
 
   - name: install updates (Ubuntu)
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Ubuntu"
  
 - hosts: web_servers
   tasks:
   - name: install apache2 ans php packages for Ubuntu
     tags: apache,apache2,ubuntu
     apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
     when: ansible_distribution == "Ubuntu"

   - name: copy html file for site
     tags: apache,apache,apache2,httpd
     copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644
